Repository Collab4exaNBody/exaDEM, pull requests merged in 2024-12, with the labels that each got.

#88 Fix CI (SPACK)
  .github/workflows/cmake.yml
  .github/workflows/spack.yml
  example/polyhedra/CMakeLists.txt
Labels: bug

#89 Speedup compute_vertices on GPU by skipping empty cells
  src/grid/include/exaDEM/cell_list_wrapper.hpp
  src/grid/update_cell_list.cpp
  src/polyhedron/polyhedra_compute_vertices.cpp
Labels: performance

#104 Add stress stensor
  data/config/config_end_iteration.msp
  data/config/config_exaDEM.msp
  data/config/config_iteration_dump.msp
  data/config/config_move_particles.msp
  data/config/config_numerical_schemes.msp
  data/config/config_start_iteration.msp
  data/config/config_stress_tensor.msp
  example/polyhedra/analyses/CMakeLists.txt
  example/polyhedra/analyses/octahedron.shp
  example/polyhedra/analyses/write_avg_stress.msp
  example/polyhedra/analyses/write_avg_stress_minimal.msp
  example/spheres/axial-stress/shear_with_xform_dem.msp
  example/spheres/impose_velocity/impose_velocity.msp
  example/spheres/impose_velocity/impose_velocity_hole.msp
  include/exanb/field_sets.h
  include/exanb/fields.h
  scripts/post_processing/avg_stress.gnu
  src/field/reset_stress.cpp
  src/interaction/avg_stress_tensor.cpp
  src/interaction/include/exaDEM/interaction/classifier.hpp
  src/interaction/include/exaDEM/interaction/classifier_for_all.hpp
  src/interaction/include/exaDEM/itools/buffer.hpp
  src/interaction/include/exaDEM/shape/shape_detection_api.hpp
  src/interaction/include/exaDEM/type/add_contribution_mat3d.hpp
  src/interaction/stress_tensor.cpp
Labels: documentation, new feature, Add example

#105 add particle map type
  example/polyhedra/analyses/common.msp
  example/polyhedra/analyses/common_minimal.msp
  example/polyhedra/analyses/interaction.msp
  example/polyhedra/analyses/interaction_minimal.msp
  example/polyhedra/analyses/write_avg_stress.msp
  example/polyhedra/analyses/write_avg_stress_minimal.msp
  example/polyhedra/analyses/write_paraview_polyhedra_minimal.msp
  example/polyhedra/analyses/write_pos_vel_minimal.msp
  example/polyhedra/balls/balls.msp
  example/polyhedra/balls/balls_mini.msp
  example/polyhedra/funnel/funnel.msp
  example/polyhedra/generator/generator.msp
  example/polyhedra/rotating_drum/rotating-drum-mini.msp
  example/polyhedra/rotating_drum/rotating-drum-mixte-mini.msp
  example/polyhedra/rotating_drum/rotating-drum-mixte.msp
  example/polyhedra/rotating_drum/rotating-drum.msp
  example/polyhedra/stl_mesh/stl_mesh_box_hexapod.msp
  example/polyhedra/stl_mesh/stl_mesh_box_hexapod_mini.msp
  example/polyhedra/stl_mesh/stl_mesh_box_mixte.msp
  example/polyhedra/stl_mesh/stl_mesh_box_mixte_mini.msp
  example/polyhedra/stl_mesh/stl_mesh_box_octahedron.msp
  example/polyhedra/stl_mesh/stl_mesh_box_octahedron_mini.msp
  example/tutorial/blade/generator.msp
  example/tutorial/hexa-rotating-drum/generator.msp
  src/interaction/include/exaDEM/shape/shape_reader.hpp
  src/interaction/read_shape_file.cpp
Labels: Factorize
